// packages/solid/lib/outlet.tsx
import { Show, useContext } from 'solid-js';
import { Dynamic } from 'solid-js/web';
import { OutletContext } from './context';
import { useOpenedViews } from './use-opened-views';

/**
 * @description Outlet component for nested routes
 * @link https://router.effector.dev/solid/outlet.html
 * @example ```tsx
 * export const RoutesView = createRoutesView({
 *   routes: [
 *     createRouteView({
 *       route: routes.profile,
 *       view: ProfileScreen,
 *       children: [
 *         createRouteView({ route: routes.settings, view: SettingsScreen }),
 *       ],
 *     }),
 *   ],
 * });
 *
 * // profile.tsx
 * export const ProfileScreen = () => {
 *   // will render settings screen when profile route is opened
 *   // and settings route is active
 *   return (
 *     <>
 *       <div>Profile</div>
 *       <Outlet />
 *     </>
 *   );
 * };
 * ```
 */
export function Outlet() {
  const { children } = useContext(OutletContext);
  const openedViews = useOpenedViews(children);
  const openedView = () => openedViews().at(-1);

  return (
    <Show when={openedView()} keyed>
      {(view) => (
        <OutletContext.Provider value={{ children: view.children ?? [] }}>
          <Dynamic component={view.view} />
        </OutletContext.Provider>
      )}
    </Show>
  );
}

// packages/react/lib/outlet.tsx
import { OutletContext } from './context';
import { createElement, useContext } from 'react';
import { useOpenedViews } from './use-opened-views';

/**
 * @description Outlet component for nested routes
 * @link https://router.effector.dev/react/outlet.html
 * @example ```ts
 * export const RoutesView = createRoutesView([
 *   createRouteView({
 *     route: routes.profile,
 *     view: ProfileScreen,
 *     children: [
 *      createRouteView({ route: routes.settings, view: SettingsScreen }),
 *     ]
 *   }),
 * ]);
 *
 * // profile.tsx
 * export const ProfileScreen = () => {
 *   // will render settings screen when profile route is opened
 *   // and settings route is active
 *   return (
 *     <>
 *       <div>Profile</div>
 *       <Outlet />
 *     </>
 *   );
 * };
 * ```
 */
export const Outlet = () => {
  const { children } = useContext(OutletContext) ?? { children: [] };
  const openedView = useOpenedViews(children).at(-1);

  if (!openedView) {
    return null;
  }

  return (
    <OutletContext.Provider value={{ children: openedView.children ?? [] }}>
      {createElement(openedView.view)}
    </OutletContext.Provider>
  );
};
