// packages/solid/lib/router-provider.tsx
import type { JSX } from 'solid-js';
import type { Router } from '@effector/router';
import { RouterProviderContext } from './context';

interface RouterProviderProps {
  children?: JSX.Element;
  router: Router;
}

/**
 * @description Provides router in Solid tree
 * @param props Router provider config
 */
export function RouterProvider(props: RouterProviderProps) {
  return (
    <RouterProviderContext.Provider value={props.router}>
      {props.children}
    </RouterProviderContext.Provider>
  );
}

// packages/react/lib/router-provider.tsx
import type { ReactNode } from 'react';
import type { Router } from '@effector/router';
import { RouterProviderContext } from './context';

interface RouterProviderProps {
  children?: ReactNode;
  router: Router;
}

/**
 * @description Provides router in React tree
 * @param props Router provider config
 */
export const RouterProvider = (props: RouterProviderProps) => {
  return (
    <RouterProviderContext.Provider value={props.router}>
      {props.children}
    </RouterProviderContext.Provider>
  );
};
