// packages/solid/lib/use-router.ts
import { useContext } from 'solid-js';
import { RouterProviderContext } from './context';
import { useUnit } from 'effector-solid';

export function useRouterContext() {
  const context = useContext(RouterProviderContext);

  if (!context) {
    throw new Error(
      '[useRouter] Router not found. Add RouterProvider in app root',
    );
  }

  return context;
}

/**
 * @description Use router from provider
 * @returns Router unit shape (Solid accessors)
 * @link https://router.effector.dev/solid/use-router.html
 */
export function useRouter() {
  return useUnit(useRouterContext());
}

// packages/react/lib/use-router.ts
import { useContext } from 'react';
import { RouterProviderContext } from './context';
import { useUnit } from 'effector-react';

export function useRouterContext() {
  const context = useContext(RouterProviderContext);

  if (!context) {
    throw new Error(
      '[useRouter] Router not found. Add RouterProvider in app root',
    );
  }

  return context;
}

/**
 * @description Use router from provider
 * @returns Router
 * @link https://router.effector.dev/react/use-router.html
 */
export function useRouter() {
  return useUnit(useRouterContext());
}
